name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Create DB
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Generate key
        run: php artisan key:generate
      - name: Create schemas
        run: php artisan migrate
      - name: Cypress run
        run: npm run test:chrome
        continue-on-error: true