name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        run: npm run test:chrome
        continue-on-error: true