name: Continuous Integration Laravel
on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Create DB
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Generate key
      run: php artisan key:generate
    - name: Create schemas
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Cypress.io
      uses: cypress-io/github-action@v1.16.1
        with: 
          browser: chrome
          start: npm start
          wait-on: http://127.0.0.1:8000
