name: Laragram tests
on:
  pull_request:
    branches: [master, development]
jobs:
  build-and-run-tests:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Lint
      uses: overtrue/phplint@master

    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Create DB
      run: touch database/database.sqlite

    - name: Install Dependencies (PHP vendors)
      run: composer install

    - name: Generate key
      run: php artisan key:generate

    - name: Create schemas
      run: php artisan migrate:fresh --seed

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npm start
        wait-on: http://localhost:8000
        config-file: cypress.json
        spec: cypress/integration/laragram/laragram.spec.js
      env:
        CYPRESS_baseUrl: http://localhost:8000

    - name: Execute unit tests via PHPUnit
      run: vendor/bin/phpunit