name: Laragram tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist && npm install
      - name: Create DB
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Generate key
        run: php artisan key:generate
      - name: Create schemas
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Cypress run
        run: npx cypress run --spec cypress/integration/laragram/laragram.spec.js
        with:
          build: npm run dev
          start: npm start
          wait-on: http://localhost:8000