name: Laragram tests
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies (PHP vendors)
        run: composer install && npm install
      - name: Create DB
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Generate key
        run: php artisan key:generate
      - name: Create schemas
        run: php artisan migrate --seed
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm run dev
          start: npm start
          spec: cypress/integration/laragram/laragram.spec.js
          wait-on: 'http://127.0.0.1:8000'